### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by sotetsuk** [sotetsuk/go-scholar#100]
# feature
- [x] Manage dependencies by GoDeps #98 
- [x] Create dummy data for developping #8
- [x] Add UA #70
- [ ] Build API server #86
- [x] Deal with BibTeX information #87
- [ ] Cross compile #105 
# bug fix
- Failing test with citation increment #91 (#8 #101 also solved this)

**Comment by sotetsuk** [comment]
#86 and #105 was postponed to future release.
