### ISSUE TITLE
[release] 0.1.0

### ISSUE THREAD

**Issue by sotetsuk** [sotetsuk/go-scholar#79]
# branch
- develop-v0.1.0
# TODO
### feature
- [x] New API desgin #72 (w/ documents@README)
- ~~[ ] create dummy data for developping #8~~ => next release
### enhancement
- [x] Add godoc #16
- [x] Add related works #78 
- [x] Add dependencies #77
### refactor
- [x] rename go-scholar => scholar #80
- [x] change query => keywords #42
